### ISSUE TITLE
Make user uploaded stamps editable

### ISSUE THREAD

**Issue by za-x-az** [reallyMilo/AnnoStamps#6]
Hello 
Would love to see the following features getting added:

1. Edit the stamps we have uploaded.
2. A download counter.
3. Voting system. can be 1-5 stars or just the classic thumbs up/down.
4. Versioning of stamps (sub-feature of edit I guess)

Other than that great work!

**Comment by reallyMilo** [comment]
Hey, yeah definitely all great suggestions!

I do have some plans for the editing, download counter and upvotes. Just need to get to it :D
