### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by tefracky** [reallyMilo/AnnoStamps#725]
Hello there,

I cannot download 2 stamps:
https://annostamps.com/stamp/clgg9cjmg009908mf0aw2wqsh
https://annostamps.com/stamp/clgk0nwg30001mf08mx8nflzf

The following page accurs:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>DYGH5NA3885T11A5</RequestId>
<HostId>
cTof7XeW1pGOidb64CZulXkPKlcPkE6yTiMqiW1QMS1vc9NKvLLVpa9GHQjzIwLW3VKcDuccwbyyOnNdA2GV4w==
</HostId>
</Error>
```

**Comment by mkcy3** [comment]
Fixed! Make sure you ctrl + F5 and try downloading again.
